const Types = {
  FETCH_CHARACTERS_REQUEST: 'game/FETCH_CHARACTERS_REQUEST',
  FETCH_CHARACTERS_SUCCESS: 'game/FETCH_CHARACTERS_SUCCESS',
  FETCH_CHARACTERS_FAILURE: 'game/FETCH_CHARACTERS_FAILURE',
  SET_ANSWER: 'game/SET_ANSWER',
  RESET: 'game/RESET'
};

export default Types;
